### ISSUE TITLE
Run a micro service from vscode

### ISSUE THREAD

**Issue by nicolaserny** [xcomponent/vscode-xcomponent#5]
- start runtime
- start bridge
...

**Comment by maurelio1234** [comment]
I'm not sure this is the right approach, I'd vote for making sure these things are easy to start by hand (e.g. from a terminal inside VS code) instead of relying too much on intelligence on the editor side.

**Comment by nicolaserny** [comment]
What I had in mind is just command to start runtime and bridge in the console (jest and cake extensions are doing the same).
But I agree it's not the much important feature...

**Comment by nicolaserny** [comment]
duplicates #76
